[package]
name = "hello-deno"
version = "0.1.0"
authors = ["axt <axt_star@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type =["cdylib"]
